name: Publish to crates.io

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'  # Matches version tags like v1.0.0, v2.1.0-alpha.1

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all-features

      - name: Check package
        run: cargo package --all-features

      - name: Publish package
        run: |
          if [[ $GITHUB_REF_NAME =~ -[a-zA-Z] ]]; then
            # If tag contains a pre-release identifier (e.g., -alpha, -beta)
            cargo publish --all-features --allow-dirty
          else
            # For regular releases
            cargo publish --all-features
          fi